# plugin.yaml
schema_version: "v2"

id: com.relaycraft.plugins.privacy-guard
name: "Privacy Guard"
version: "1.0.0"
description: "Detects and prevents Personally Identifiable Information (PII) leakage in API traffic."
locales:
  zh:
    name: "隐私卫士"
    description: "检测并防止 API 流量中的个人身份信息 (PII) 泄露。"
author: "RelayCraft Security"
icon: "shield"

engines:
  relaycraft: ">=1.0.0"

capabilities:
  ui:
    entry: "index.js"
  i18n:
    namespace: plugin_privacy
    locales:
      en: locales/en.json
      zh: locales/zh.json
  logic:
    entry: "guardian.py"

permissions:
  - "proxy:write"
  - "logging:write"
